Try running GKE job for real

diff --git a/.github/workflows/ci_pytorch.yml b/.github/workflows/ci_pytorch.yml
--- a/.github/workflows/ci_pytorch.yml
+++ b/.github/workflows/ci_pytorch.yml
@@ -81,7 +81,23 @@ jobs:
 
       - name: Deploy the job on the kubernetes cluster
         run: |-
-          ls && \
-          job_name=$(jsonnet -J . ci_pytorch/tpu_test.jsonnet --ext-str image=$IMAGE --ext-str image-tag=$IMAGE_TAG) && \
-          echo $job_name
+          job_name=$(jsonnet -J . ci_pytorch/tpu_test.jsonnet --ext-str image=$IMAGE --ext-str image-tag=$IMAGE_TAG | kubectl create -f -) && \
+          job_name=${job_name#job.batch/} && \
+          job_name=${job_name% created} && \
+          echo "Waiting on kubernetes job: $job_name" && \
+          i=0 && \
+          status_code=2 && \
+          # Check on the job periodically. Set the status code depending on what
+          # happened to the job in Kubernetes. If we try MAX_CHECKS times and
+          # still the job hasn't finished, give up and return the starting
+          # non-zero status code.
+          while [ $i -lt $MAX_CHECKS ]; do ((i++)); if kubectl get jobs $job_name -o jsonpath='Failed:{.status.failed}' | grep "Failed:1"; then status_code=1 && break; elif kubectl get jobs $job_name -o jsonpath='Succeeded:{.status.succeeded}' | grep "Succeeded:1" ; then status_code=0 && break; else printf "." ; fi; sleep $CHECK_SPEED; done && \
+          echo "Done waiting. Job status code: $status_code" && \
+          pod_name=$(kubectl get po -l controller-uid=`kubectl get job $job_name -o "jsonpath={.metadata.labels.controller-uid}"` | awk 'match($0,!/NAME/) {print $1}') && \
+          echo "GKE pod name: $pod_name" && \
+          kubectl logs -f $pod_name --container=train && \
+          echo "Done with log retrieval attempt." && \
+          # If building a single-use Docker image for this test, maybe delete.
+          # gcloud container images delete "$IMAGE:$GITHUB_RUN_ID" --force-delete-tags && \
+          exit $status_code
         shell: bash
